#!/bin/sh

USER=root
NAME=calabard
VIRTUALENV=%(virtualenv_dir)s
DAEMON=$VIRTUALENV/bin/$NAME
PIDFILE=/var/run/$NAME.pid
LOGFILE=/var/log/calabar/$NAME.log
ERR_LOGFILE=/var/log/calabar/$NAME_err.log

[ -x "$DAEMON" ] || echo "Daemon not found at $DAEMON"
[ -x "$DAEMON" ] || exit 0

#
# Function that stops the daemon/service
#
do_stop()
{
        # Return
        #   0 if daemon has been stopped
        #   1 if daemon was already stopped
        #   2 if daemon could not be stopped
        #   other if a failure occurred
        start-stop-daemon --stop --retry 10 --pidfile $PIDFILE --name $NAME --user $USER
        rm -f $PIDFILE
}

do_start()
{
	start-stop-daemon --start --exec $DAEMON --name $NAME --pidfile $PIDFILE --background --make-pidfile --chuid $USER --user $USER > $LOGFILE &> $ERR_LOGFILE
}

case "$1" in
  start)
        echo "Stopping any running daemons..."
        do_stop
        echo "Starting $NAME..."
        do_start
	;;
  stop)
        echo "Stopping $NAME..."
        do_stop
	;;
  *)
	echo "Usage: $NAME {start|stop}" >&2
	exit 3
	;;
esac

:
